In [ ]:
# 설치 명령어
!pip3 install torch torchvision torchaudio

## 01. 텐서 초기화

In [2]:
import torch
import numpy as np


torch.__version__

'2.5.1+cu121'

### 1-1. 초기화 되지 않는 문서

In [6]:
tensor = torch.empty(4,2)
print(tensor)

tensor([[ 7.5095e+18,  4.4232e-41],
        [ 5.3514e-07,  4.4233e-41],
        [-1.7519e+29,  4.4232e-41],
        [ 9.1084e-44,  0.0000e+00]])


### 1-2. 상수로 초기화된 텐서


In [ ]:
a = torch.ones(3,4,dtype=torch.long) # dtype 데이터 타입 지정
b= torch.zeros(2,2)
print(a)
print(b)

### 1-3 무작위로 초기화된 tensor
- torch.rand : 0~1사이의 값으로 무작위로 초기화
- torch.randn : 표준정규분포에성 무작위로 초기화

In [7]:
a = torch.rand(3,3)
b = torch.randn(2,2)
print(a,b)

tensor([[0.4709, 0.2421, 0.8032],
        [0.7426, 0.4879, 0.5712],
        [0.6580, 0.8210, 0.8210]]) tensor([[ 0.1533, -1.1306],
        [-0.1087,  1.2859]])


### 1-4 직접 입력한 값으로 초기화

In [8]:
a = torch.tensor([1,2.3])
a

tensor([1.0000, 2.3000])

### 1-5. Numpy 배열로부터 초기화

In [11]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)
a

array([1. , 2.3], dtype=float32)

### 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [12]:
a = torch.ones(3,4,dtype=torch.long) # dtype 데이터 타입 지정
b = torch.rand_like(a,dtype=torch.float)
b

tensor([[0.3789, 0.9592, 0.8660, 0.9734],
        [0.2048, 0.0839, 0.1225, 0.2273],
        [0.3980, 0.4017, 0.6868, 0.0926]])

### 1-7.텐서의 속성

In [2]:
tensor = torch.rand(3,4,dtype=torch.float64)

print(tensor.size())
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


### 1-8. 특정 타입의 텐서 생성

In [4]:
tensor = torch.rand(3,4,dtype=torch.float64)

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype)
int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.dtype)

torch.float32


torch.int32

### 1-9. 데이터 타입 캐스팅

In [ ]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())
int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())

### 1-10. CUDA Tensor

In [3]:
tensor = torch.rand(3,4,dtype=torch.float64)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

### 1-11. 다차원 텐서 표현

#### 1-11-1. 0D Tensor(Scaler)
- 하나의 값을 담고 있는 텐서

In [10]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


#### 1-11-2. 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서

In [12]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-3. 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재

In [11]:
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


#### 1-11-4. 3D Tensor(Cube)
- 큐브와 같은 형태로 세 개의 축이 존재

In [15]:
t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]],
                   [[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


#### 1-11-5. 4D Tensor(Tensor)
- 4개의 축

In [17]:
t4 = torch.rand(2, 3, 4, 5) # 4차원 텐서: 가장 바깥쪽은 2개의 그룹, 각 그룹에 3개의 하위 그룹, 각 하위 그룹은 4행 5열로 구성
t4

tensor([[[[0.4309, 0.3418, 0.1072, 0.4704, 0.4902],
          [0.2015, 0.9097, 0.6205, 0.4023, 0.9026],
          [0.4891, 0.3370, 0.3433, 0.1026, 0.9542],
          [0.3909, 0.6142, 0.2023, 0.9321, 0.1706]],

         [[0.2121, 0.8729, 0.1787, 0.1373, 0.5362],
          [0.4323, 0.1665, 0.2646, 0.9361, 0.7967],
          [0.4919, 0.2301, 0.4083, 0.8250, 0.0600],
          [0.4336, 0.2898, 0.9019, 0.1342, 0.5242]],

         [[0.9935, 0.8623, 0.1334, 0.5391, 0.7794],
          [0.8170, 0.8390, 0.9996, 0.9785, 0.7858],
          [0.8803, 0.9851, 0.0071, 0.5720, 0.5424],
          [0.9131, 0.2597, 0.4449, 0.0862, 0.8686]]],


        [[[0.7992, 0.5036, 0.4880, 0.9320, 0.5803],
          [0.8578, 0.9032, 0.0553, 0.4886, 0.8656],
          [0.9975, 0.4100, 0.6937, 0.2524, 0.1463],
          [0.1763, 0.4935, 0.6443, 0.0904, 0.8909]],

         [[0.3712, 0.1422, 0.5607, 0.8055, 0.9552],
          [0.6015, 0.9019, 0.2598, 0.3220, 0.1141],
          [0.8280, 0.7971, 0.4271, 0.0524, 0.8698],
  