In [2]:
import torch

### 2-1. 산술 연산

In [3]:
tensor = torch.rand(2, 3)
print(tensor)
tensor = tensor * 2
print(tensor)

tensor([[0.0727, 0.9800, 0.0753],
        [0.5842, 0.2026, 0.5455]])
tensor([[0.1455, 1.9600, 0.1505],
        [1.1683, 0.4052, 1.0909]])


#### 덧셈

In [9]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
add = torch.add(x,y) # 덧셈
y.add_(x)
print(y)


tensor([[0.8917, 0.1978],
        [0.8140, 1.3470]])


#### 뺄셈

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
sub = torch.sub(x,y) # 뺄셈
print(sub)

#### 곱셈

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
mul = torch.mul(x,y) # 곱셈
print(mul)

#### 나눗셈

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
div = torch.div(x,y) # 나눗셈
print(div)

### 2-2 각종 연산

In [4]:
a = torch.tensor(-10)
print("절댓값",torch.abs(a))

b = torch.tensor(3.3)
print("올림",torch.ceil(b))
print("반올림",torch.round(b))
print("반올림",torch.floor(b))

c = torch.tensor([[0.8,0.3],[-0.9,0.4]])
print("클램프",torch.clamp(c,min = - 0.5, max = 0.5))

절댓값 tensor(10)
올림 tensor(4.)
반올림 tensor(3.)
반올림 tensor(3.)
클램프 tensor([[ 0.5000,  0.3000],
        [-0.5000,  0.4000]])


In [ ]:
x = torch.randn(2,2)
y = torch.tensor([[1,2],[3,4]])
print("최솟값",torch.min(x))
print("최댓값",torch.max(x))
print("평균",torch.mean(x))
print("분산",torch.var(x))
print("표준편차",torch.std(x))
print("모든 원소의 합",torch.sum(x))
print("모든 원소의 합",torch.sum(y,dim=0))
print("모든 원소의 곱",torch.prod(y))
print("중복된 값 제거",torch.unique(torch.tensor([1,2,2,2,2,2,2,3,3,3,3])))

### 2-3 내적(dot product)

In [3]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])
result = torch.matmul(x,y)
print(result)

tensor([[19, 22],
        [43, 50]])
