## 03. Tensor의 조작

### 3-1. 인덱싱, 슬라이싱
- Numpy 처럼 활용

In [4]:
import torch
import numpy as np

In [13]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1]) # 슬라이싱
print(tensor[0,:])

a = torch.tensor([1,2,3,4,5])
print(a[-3:]) # 슬라이싱

b = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
c = b[b>3] # 조건으로 인덱싱
d = b[b%2==0]
e = b[[0,1],[1,2]]
e

tensor(2)
tensor([1, 2])
tensor([3, 4, 5])


tensor([2, 6])

### 3-2. Tensor의 크기, 모양 변경

In [ ]:
t = torch.rand(4,5)
print(t)
x = t.view(5,4)
print(x)

### 3-3. Tensor의 숫자 값 얻기

In [11]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y.item())

10
0.16102313995361328


### 3-4. 차원 축소와 증가

#### 3-4-1. 차원 축소
- torch.squeeze() : 크기가 1인 차원을 축소함

In [15]:
t = torch.rand(1,3,3)
print(t.shape)
ts = torch.squeeze(t)
print(ts.shape)

torch.Size([1, 3, 3])
torch.Size([3, 3])


### 3-4-2. 차원 증가(생성)
- torch.unsqueeze() : 지정한 위치에 새로운 차원을 생성

In [ ]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)
ts = torch.unsqueeze(t,0)
print(ts)
print(ts.shape)

### 3-5. 텐서간 결합

- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화 함
  - 새로운 차원이 생성 됨

In [ ]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])
z = torch.stack([x,y])
print(z)
print(z.shape)

- torch.cat() : 하나의 텐서로 병합
  - 새로운 차원이 생성되지는 않음
  - 내부 원소의 크기는 같을 필요는 없지만, 각각의 개수는 같아야한다

In [19]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.cat((x,y),dim = 0)
print(z)
print(z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


### 3-6 Tensor 나누기

- torch.chunk()
  - 텐서를 몇개로 나눌지 지정
  - 나누어 떨어지지 않으면 마지막 조각은 크기가 다를 수 있음

In [25]:
t = torch.rand(3,3)
print(t)

a,b,c = torch.chunk(t,3,dim = 0)
print(a)
print(b)
print(c)

tensor([[0.8753, 0.7251, 0.9422],
        [0.5991, 0.1023, 0.7598],
        [0.9165, 0.8589, 0.8236]])
tensor([[0.8753, 0.7251, 0.9422]])
tensor([[0.5991, 0.1023, 0.7598]])
tensor([[0.9165, 0.8589, 0.8236]])


- torch.split()
  - 텐서의 크기를 기준으로 나눔

In [33]:
t = torch.rand(3,6)
print(t)

x,y = torch.split(t, 3, dim=1)
print(x)
print(y)

tensor([[0.9193, 0.1660, 0.2780, 0.4769, 0.8561, 0.7009],
        [0.2293, 0.4000, 0.6322, 0.4495, 0.0536, 0.2830],
        [0.5602, 0.4665, 0.5623, 0.3090, 0.1045, 0.6103]])
tensor([[0.9193, 0.1660, 0.2780],
        [0.2293, 0.4000, 0.6322],
        [0.5602, 0.4665, 0.5623]])
tensor([[0.4769, 0.8561, 0.7009],
        [0.4495, 0.0536, 0.2830],
        [0.3090, 0.1045, 0.6103]])
