## 08. 이진화
- 임계값을 기준으로 색상을 흰색과 검은색으로 나누는 것

In [20]:
import cv2
import numpy as np

BOOK = "images/book.jpg"
DOG_Path = "images/dog.jpg"
DOG_Path2 = "images/dog.png"

### 8-1. 기본 이진화
- ret, binary = cv2.threshold()
- 임계값이 높아지면 검은색 낮아지면 흰색

In [ ]:
img = cv2.imread(BOOK,cv2.IMREAD_GRAYSCALE)

ret, binary = cv2.threshold(img,127, 255,cv2.THRESH_BINARY) # cv2함수는 이진화의 옵션 

cv2.imshow("img",img)
cv2.imshow("binary",binary)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [17]:
img = cv2.imread(DOG_Path)
name = "Trackbar"
trackbar_name = "Rotation"
# 이미지를 출력하기 전에 트랙바가 생성될 window가 먼저 존재해야 함.
cv2.namedWindow(name)
cv2.createTrackbar(trackbar_name, name, 0, 360, lambda x: x)

while True:
    angle = cv2.getTrackbarPos(trackbar_name, name) # Trackbar의 값을 가져온다
    center = (img.shape[1]/2, img.shape[0]/2)
    affine = cv2.getRotationMatrix2D(center, angle, 2)
    dst = cv2.warpAffine(img, affine, (img.shape[1], img.shape[0]))
    cv2.imshow(name, dst)

    if cv2.waitKey(1) == ord("q"):
        break

cv2.destroyAllWindows()


In [16]:
import cv2

# 콜백 함수 (트랙바가 움직일 때 호출됨)
def on_trackbar(val):
    # 트랙바에서 가져온 임계값을 사용하여 이진화 수행
    _, binary = cv2.threshold(img, val, 255, cv2.THRESH_BINARY)
    # 이진화된 이미지를 업데이트하여 표시
    cv2.imshow("binary", binary)

# 이미지를 그레이스케일로 읽어오기
img = cv2.imread(BOOK, cv2.IMREAD_GRAYSCALE)

# 윈도우 생성
cv2.imshow("img", img)
cv2.imshow("binary", img)  # 초기 상태로 원본 이미지 표시

# 트랙바 추가
cv2.createTrackbar("Threshold", "binary", 127, 255, on_trackbar)

# 키 입력 대기
cv2.waitKey(0)
cv2.destroyAllWindows()


## 실습 2-2 Threshold에 적용

In [28]:
import cv2

# 이미지를 그레이스케일로 읽어오기 (BOOK 파일 경로 필요)
img = cv2.imread(BOOK, cv2.IMREAD_GRAYSCALE)

# 윈도우 이름 및 트랙바 이름 설정
name = "binary"  # 출력 윈도우 이름
trackbar_name = "threshold"  # 트랙바 이름

# 트랙바를 추가하기 위한 윈도우 생성
cv2.namedWindow(name)

# 트랙바 생성
# 트랙바 이름: threshold, 초기값: 127, 최대값: 255, 콜백 함수: on_trackbar
cv2.createTrackbar(trackbar_name, name, 127, 255, lambda x: x)

# 무한 루프 시작 (트랙바 값을 실시간으로 적용)
while True:
    # 트랙바에서 현재 임계값을 가져옴
    threshold = cv2.getTrackbarPos(trackbar_name, name)
    
    # 이진화 수행 (현재 임계값 사용)
    ret, binary = cv2.threshold(img, threshold, 255, cv2.THRESH_BINARY)
    
    # 이진화된 이미지 출력
    cv2.imshow(name, binary)

    # 'q' 키를 누르면 루프 종료
    if cv2.waitKey(1) == ord("q"):
        break

# 모든 윈도우 닫기
cv2.destroyAllWindows()


### 컬러팔레트 만들기

In [18]:
import cv2
import numpy as np
# 윈도우 이름 및 트랙바 이름 설정
merge_color = np.zeros((300, 500, 3), dtype=np.uint8) 
name = "image"  # 출력 윈도우 이름
RED = "R"  # 트랙바 이름
GREEN = "G"  # 트랙바 이름
BLUE = "B"  # 트랙바 이름
ON_OFF ="ON_OFF"

# 트랙바를 추가하기 위한 윈도우 생성
cv2.namedWindow(name)

cv2.createTrackbar(RED, name, 0, 255, lambda x: x)
cv2.createTrackbar(GREEN, name, 0, 255, lambda x: x)
cv2.createTrackbar(BLUE, name, 0, 255, lambda x: x)
cv2.createTrackbar(ON_OFF, name, 0, 1, lambda x: x)

while True:
    red = cv2.getTrackbarPos(RED, name)
    green = cv2.getTrackbarPos(GREEN, name)
    blue = cv2.getTrackbarPos(BLUE, name)
    onoff = cv2.getTrackbarPos(ON_OFF, name)
    
    if onoff == 1:
        merge_color[:] = [blue,green,red]
    else:
        merge_color[:] = [0,0,0]

    cv2.imshow(name,merge_color)

    if cv2.waitKey(1) == ord("q"):
        break
cv2.destroyAllWindows()


### 8-2. 적응형 이진화
- 블록마다 다른 임계값을 적용
- C값이 커지면 임계값이 커져서 밝은 영역이 많아진다.

In [24]:
img = cv2.imread(BOOK,cv2.IMREAD_GRAYSCALE)
name = "Adaptive"
cv2.namedWindow(name)

cv2.createTrackbar("block_size",name,25,100,lambda x:x) # 1보다 큰 홀수만 가능
cv2.createTrackbar("C",name,1,10,lambda x:x)

while True:
    block_size = cv2.getTrackbarPos("block_size",name)
    C = cv2.getTrackbarPos("C",name)

    if block_size <= 1:
        block_size = 3
    if block_size%2 == 0:
        block_size += 1

    binary = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,block_size,C)

    cv2.imshow(name,binary)

    if cv2.waitKey(1) == ord("q"):
        break
cv2.destroyAllWindows()