## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
t1 = torch.tensor([2,4,6])
print(t1+5)
print(t1-5)

tensor([ 7,  9, 11])
tensor([-3, -1,  1])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [7]:
x = torch.rand(3,3)
y = torch.rand(3,3)
add = torch.add(x,y)
sub = torch.sub(x,y)
mul = torch.mul(x,y)
div = torch.div(x,y)
print(add)
print(sub)
print(mul)
print(div)

tensor([[1.7313, 0.8605, 0.9953],
        [1.7867, 1.4054, 0.9476],
        [0.9367, 0.9222, 0.4689]])
tensor([[ 0.1485,  0.5522,  0.4752],
        [-0.1476, -0.0886, -0.1369],
        [-0.4656, -0.2879, -0.0149]])
tensor([[0.7438, 0.1089, 0.1912],
        [0.7927, 0.4918, 0.2198],
        [0.1651, 0.1919, 0.0549]])
tensor([[1.1877, 4.5813, 2.8275],
        [0.8474, 0.8814, 0.7475],
        [0.3359, 0.5241, 0.9382]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [19]:
A = torch.tensor([[1,2,3], [4,5,6]])
B = torch.tensor([[7,8],[9,10],[11,12]])
print(torch.matmul(A,B))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [20]:
R = torch.matmul(A,B)
print(R)
print(torch.clamp(R+10, max = 100))

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [23]:
import torch

M = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

result = torch.sum(M, dim=0)
print("각 열의 합계:", result)


각 열의 합계: tensor([55, 60, 65, 70, 75])
